// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onExternalTemperatureValueChange();
void onRelayDurationChange();
void onRelayStateChange();
void onRelaystate2Change();

int externalTemperatureValue;
int relayDuration;
int temperature;
int waterPercentage;
bool relayState;
bool relaystate2;

void initProperties(){

  ArduinoCloud.addProperty(externalTemperatureValue, READWRITE, ON_CHANGE, onExternalTemperatureValueChange);
  ArduinoCloud.addProperty(relayDuration, READWRITE, ON_CHANGE, onRelayDurationChange);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(waterPercentage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relayState, READWRITE, ON_CHANGE, onRelayStateChange);
  ArduinoCloud.addProperty(relaystate2, READWRITE, ON_CHANGE, onRelaystate2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
